added unit test on middlewares settings
r2d2bzh/broker-autobot pull request #3
Opened 2020-12-03 14:24 UTC by alshyra

2020-12-03 16:05 UTC, alshyra commented
@gautaz je suis prêt

2020-12-08 10:24 UTC, gautaz requested changes
A minor detail

2020-12-08 10:24 UTC, gautaz commented on src/broker-revolver.js
> + * @param {Function} nodeID
Function or function ?

2020-12-08 10:41 UTC, alshyra commented on src/broker-revolver.js
> + * @param {Function} nodeID
Function :)

2020-12-08 10:43 UTC, gautaz approved these changes
LGTM

2020-12-08 10:44 UTC, merged